version: '3.8'
services:

#------------------------ mysql ---------------------------
  mysql:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
#      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    volumes:
      - '~\Documents\Dev\MySQL:/var/lib/mysql'
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

#------------------------ EitanMedical Server ---------------------------    
  eitan-medical:
    container_name: eitan-medical
    build:
      context: .
      dockerfile: Dockerfile  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - DB_CONNECTION_STRING=server=host.docker.internal;Port=3306;user=root;password=qwerty;database=EitanMedicalDb
      - LOG_FOLDER=Log
    restart: unless-stopped
    ports:
      - 80:80
      - 5000:5000
    volumes:
      - C:\Log:/app/Log
    depends_on:
      - mysql
      
#------------------------ IoT Services  ---------------------------    
  iot-services:
    container_name: iot-services
    build:
      context: .
      dockerfile: Dockerfile2  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:81
      - LOG_FOLDER=Log
      - PathFile=Patients
      - EitanMedicalUrl=http://eitan-medical:80
      - Communication__Patient__API__SendAllPatients=api/Patient/AddListPatients
      - Communication__Patient__API__SendPatient=api/Patient/AddPatient
      - Communication__HeartRateReading__API__SendAllHeartRateReadings=api/HeartRateReading/AddListHeartRateReadings
      - Communication__HeartRateReading__API__HeartRateReading=api/HeartRateReading/AddHeartRateReading
    restart: unless-stopped
    ports:
      - 81:81
    volumes:
      - C:\Patients:/app/Patients
      - C:\Log:/app/Log
    depends_on:
      - mysql